# Generated by Django 5.2 on 2025-04-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='dados',
        ),
    ]
